name: pytorch_3dunet_dev

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.0.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - aom=3.7.1
  - attrs=23.2.0
  - blas=1.0
  - blinker=1.7.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.24.0
  - c-blosc2=2.12.0
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=41.0.7
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - dav1d=1.2.1
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - giflib=5.2.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - google-auth=2.26.0
  - google-auth-oauthlib=1.2.0
  - grpcio=1.60.0
  - h5py=3.10.0
  - hdf5=1.14.3
  - idna=3.6
  - imagecodecs=2024.1.1
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - intel-openmp=2022.1.0
  - jinja2=3.1.2
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.21.2
  - lazy_loader=0.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libavif16=1.0.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcurl=8.5.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgrpc=1.60.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markdown=3.5.1
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.4
  - ncurses=6.4
  - networkx=3.2.1
  - numpy=1.26.3
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.2
  - pillow=10.2.0
  - pip=23.3.2
  - protobuf=4.24.4
  - pthread-stubs=0.4
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=23.3.0
  - pysocks=1.7.1
  - python=3.11.7
  - python_abi=3.11
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - rav1e=0.6.6
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-image=0.22.0
  - scipy=1.11.4
  - setuptools=69.0.3
  - six=1.16.0
  - snappy=1.1.10
  - svt-av1=1.8.0
  - sympy=1.12
  - tensorboard=2.15.1
  - tensorboard-data-server=0.7.0
  - tifffile=2023.12.9
  - tk=8.6.13
  - torchtriton=2.1.0
  - tqdm=4.66.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
